### ISSUE TITLE
Please remove these files

### ISSUE THREAD

**Issue by reunono** [AcCodo/project-ink#2]
Hello, <br/> <br/>I'm the creator of the Corgi Engine, and this repository is sharing all of the asset's contents. Unfortunately, this is against the asset store's terms and conditions, and you can't redistribute it publicly like that.Please remove these files from this repository within the next 24 hours, or make the repository private. <br/>After that delay Github will take that repo down. <br/> <br/>Thanks, <br/>Renaud

**Comment by AcCodo** [comment]
Hi reunono, just brought my repo to public settings again after removing the CorgiEngine files. Is this corrected now? I just want to make sure I did everything correctly

**Comment by AcCodo** [comment]
Hi Renaud,

I'm really sorry for that, this wasn't done on purpose. I'll remove the
files as soon as I get to my computer
